let songs = [
  {
    id: 2301,
    Track: "The sacrament",
    Artist: "H.I.M",
    Year: 2005,
    Album: "Love metal",
    Artwork: "love-metal",
    Genre: "Love metal",
    Duration: "04:30",
    Mood: "Relaxing",
    Core: "The sacrament of love is true, the sacrament is you.",
    Free: true,
  },
  {
    id: 2302,
    Track: "Brandon Lee",
    Artist: "The 69 eyes",
    Year: 2000,
    Album: "Blessed be",
    Artwork: "blessed-be",
    Genre: "Gothic rock",
    Duration: "03:28",
    Mood: "Sad",
    Core: "We rise and shine and fall.",
    Playlists: "Soft_electric",
  },
  {
    id: 2303,
    Track: "Cirice",
    Artist: "Ghost",
    Year: 2010,
    Album: "Circie",
    Artwork: "cirice",
    Genre: "Heavy metal",
    Mood: "Heroic",
    Core: "Can't you see that you're lost without me?",
  },
  {
    id: 2304,
    Track: "Another life",
    Artist: "Motionless in white",
    Year: 2019,
    Album: "Disguise",
    Genre: "Metalcore",
    Duration: "03:25",

    Mood: "Sad",
    Core: "But I hate that it seems, you were never enough.",
  },
  {
    id: 2305,
    Track: "Dead memories",
    Artist: "Slipknot",
    Year: 2003,
    Album: "All hope is gone",
    Artwork: "all-hope-is-gone",
    Genre: "Heavy metal, Hard rock",
    Duration: "04:28",
    Mood: "Relaxing",
    Core: "Dead visions in your name...",
    Playlists: "Hard_electric",
  },
  {
    id: 2306,
    Track: "The chant",
    Artist: "Gojira",
    Year: 2023,
    Album: "Fortitude",
    Artwork: "solitude",
    Genre: "Groove-progressive metal",
    Duration: "05:12",
    Mood: "Happy",
    Core: "Get a hold of yourself, rise above",
    Playlists: "Hard_electric",
  },
  {
    id: 2307,
    Track: "Dark secret love",
    Artist: "H.I.M",
    Year: 2002,
    Album: "Demo tape",
    Artwork: "villes-mom",
    Genre: "Hard-gothic rock",
    Duration: "05:20",
    Mood: "Dark",
    Core: "And please let me come closer",
    Playlists: "Hard_electric",
    Free: true,
  },
  {
    id: 2308,
    Track: "Snuff",
    Artist: "Slipknot",
    Year: 2003,
    Album: "All hope is gone",
    Artwork: "all-hope-is-gone",
    Genre: "Nu metal, rock",
    Duration: "04:36",
    Mood: "Sad",
    Core: "So if you love me, let me go.",
    Playlists: "Soft_electric",
  },
  {
    id: 2309,
    Track: "Wasting the dawn",
    Artist: "The 69 Eyes",
    Year: 2006,
    Album: "?",
    Artwork: "wasting-the-dawn",
    Genre: "Alternative rock",
    Duration: "05:21",
    Mood: "Sad",
    Core: "Been waiting for you for so long.",
    Playlists: "Soft_electric",
  },
  {
    id: 2310,
    Track: "The phantom gate",
    Artist: "H.I.M",
    Year: 1995,
    Album: "Demo tape",
    Artwork: "phantom-gate",
    Genre: "Hard-gothic rock",
    Duration: "04:38",
    Mood: "Sad",
    Core: "There are things you should know...",
    Playlists: "Hard_electric",
  },
  {
    id: 2311,
    Track: "I love the darkness in you",
    Artist: "The 69 eyes",
    Year: 2012,
    Album: "X",
    Artwork: "x",
    Genre: "Gothic rock",
    Duration: "03:19",
    Mood: "Happy",
    Core: "Darkness in you, so dirty, and blue.",
    Playlists: "Soft_electric",
  },
  {
    id: 2312,
    Track: "In joy and sorrow",
    Artist: "H.I.M",
    Year: 2001,
    Album: "Deep shadows and brilliant highlights",
    Artwork: "deep-shadows-and-brilliant-highlights",
    Genre: "Gothic rock",
    Duration: "03:59",
    Mood: "Relaxing",
    Core: "My home's in your arms.",
    Playlists: "Soft_electric",
  },
  {
    id: 2313,
    Track: "The funeral of hearts",
    Artist: "H.I.M",
    Year: 2005,
    Album: "Love metal",
    Artwork: "love-metal",
    Genre: "Love metal",
    Duration: "04:30",
    Mood: "Relaxing",
    Core: "A prayer to a god, who's deaf and blind.",
    Playlists: "Soft_electric",
  },
  {
    id: 2314,
    Track: "Venus doom",
    Artist: "H.I.M",
    Year: 2007,
    Album: "Venus doom",
    Artwork: "venus-doom",
    Genre: "Doom metal, hard rock",
    Duration: "05:08",
    Mood: "Sad",
    Core: "Don't loose yourself in this suffering yet.",
    Playlists: "Soft_electric",
  },
  {
    id: 2315,
    Track: "My twin",
    Artist: "Katatonia",
    Year: 2006,
    Album: "Great cold distance",
    Artwork: "my-twin",
    Genre: "Alternative metal",
    Duration: "03:41",
    Mood: "Sad",
    Core: "It feels like fire, but it won't last.",
    Playlists: "Soft_electric",
  },
  {
    id: 2316,
    Track: "Nothing else matters",
    Artist: "Metallica",
    Year: 1991,
    Album: "Single",
    Artwork: "nothing-else",
    Genre: "Acoustic rock, metal",
    Duration: "06:28",
    Mood: "Sad",
    Core: "So close, no matter how far.",
    Playlists: "Soft_electric",
  },
  {
    id: 2317,
    Track: "Heartless",
    Artist: "H.I.M",
    Year: 1997,
    Album: "Greatest love songs",
    Artwork: "villes-mom",
    Genre: "Hard-gothic metal",
    Duration: "07:22",
    Mood: "Sad",
    Core: "Your pain is not love.",
    Playlists: "Hard_electric",
  },
];

export const getSongs = () => songs;
